[package]
name = "bast-homework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osmpbfreader = "0.16.1"
rand = "0.8.5"

[[bin]]
name = "basic-algos"
path = "src/basic-algos.rs"
